// script.js

// 選擇提示元素並添加到結構中
document.querySelectorAll('.element').forEach(element => {
    element.addEventListener('click', function() {
        const type = this.getAttribute('data-type');
        addElementToStructure(type);
    });
});

// 添加元素到架構編輯區
function addElementToStructure(type) {
    const structureEditingArea = document.getElementById('structureEditingArea');
    const newElement = document.createElement('div');
    newElement.classList.add('structure-element', type);
    newElement.textContent = type;
    newElement.addEventListener('click', function() {
        editVariable(this);
    });
    structureEditingArea.appendChild(newElement);
}

// 編輯選定元素的變數
function editVariable(element) {
    const variableInput = document.getElementById('variableInput');
    variableInput.value = element.textContent;
    variableInput.addEventListener('input', function() {
        element.textContent = this.value;
    });
}

// 生成最終提示詞
function generatePrompt() {
    const structureEditingArea = document.getElementById('structureEditingArea');
    let prompt = '';
    structureEditingArea.querySelectorAll('.structure-element').forEach(element => {
        prompt += element.textContent + ' ';
    });
    return prompt.trim();
}

// 複製到剪貼簿
document.getElementById('copyToClipboardButton').addEventListener('click', function() {
    const prompt = generatePrompt();
    navigator.clipboard.writeText(prompt).then(() => {
        alert('提示詞已複製到剪貼簿');
    });
});

// Generated by Copilot